# Generated by Django 4.2.20 on 2025-04-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_storagestatistics_actual_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='files.file'),
        ),
    ]
